### ISSUE TITLE
Mesen2 support?

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [IsoFrieze/DiztinGUIsh#104]
I prefer Mesen2's debugger and I never touch bsnes+'s debugger...

**Comment by binary1230** [comment]
I unfortunately don't have the bandwidth to implement this but, if you want you can view the source for how the protocol is implemented for tracelog capture and port it to Mesen2.  it's probably pretty easy to grab the same data inside the Mesen2 debugger (I guess, haven't looked).

But, the issue comes with the performance.  the tracelog capture does some intense multi-threaded compression tricks/etc to deal with the sheer gigantic firehose of data.  that would have to be replicated in Mesen2 as well (which, maybe it can be without a lot of problems).

So yea, sorry probably won't get to it.

You can see the BSNES implementation diff here:
https://github.com/devinacker/bsnes-plus/pull/268/files
